%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\kutla\Documents\GitHub\thesis\b_h_430F.csv
%
% Auto-generated by MATLAB on 09-Dec-2022 13:42:57

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["H_Oe", "B_Gauss"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
bh430F = readtable("C:\Users\kutla\Documents\GitHub\thesis\b_h_430F.csv", opts);


%% Clear temporary variables
clear opts